# Configuración de Nixpacks para Krayin CRM

[phases.setup]
  aptPkgs = ['git', 'curl', 'libpng-dev', 'libonig-dev', 'libxml2-dev', 'libzip-dev', 'zip', 'unzip', 'libicu-dev', 'zlib1g-dev', 'libfreetype6-dev', 'libjpeg-dev', 'libgmp-dev', 'netcat-openbsd']

[phases.install]
  cmds = [
    'docker-php-ext-configure gd --with-freetype --with-jpeg',
    'docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip calendar intl soap xml',
    'pecl install redis && docker-php-ext-enable redis',
    'a2enmod rewrite',
    'curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs',
    'composer install --optimize-autoloader --no-dev',
    'npm install',
    'npm run production',
    'php artisan key:generate',
    'php artisan krayin-crm:install',
    'php artisan config:cache'
  ]

[phases.start]
  cmd = "php artisan serve --host=0.0.0.0 --port=8090"
